name: Deploy App
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Sync Server
        run: |
          curl -X POST "https://voila-api.mmopro.in/sync-app"             -H "Content-Type: application/json"             -d '{"app": "testapp1-1761151304464", "repo": "https://github.com/BharatSharma34/testapp1-1761151304464.git"}'